language: php
php:
- 7.0
- 7.1
- 7.2
env:
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
- vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
- vendor/bin/phpcs --standard=PSR2 ./src
- vendor/bin/phpcs --standard=PSR2 ./tests
after_success:
- php vendor/bin/php-coveralls -v
notifications:
  email:
    recipients:
      - developers@theiceagency.co.uk